/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thiruvathukal.ds;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAlwaysPasses() {
        //App classUnderTest = new App();
        int i = 5;
        assert(i == 5);
    }
}
